"""Generate the Verifpal model set for the hybrid handshake from one template.

Five models come out, and they are only meaningful together:

  hybrid_auth.vp                  the design as implemented, no compromise
  hybrid_auth_classical_leaked.vp the classical long-term signing key leaks
  hybrid_auth_pq_leaked.vp        the post-quantum long-term signing key leaks
  hybrid_auth_both_leaked.vp      both leak -- the negative control
  hybrid_auth_classical_only.vp   the design with the PQ check removed, classical key leaked

The first three are the hybrid claim: losing either half is survivable. The last two
are controls: they must FAIL, because a model whose queries cannot fail proves
nothing. The `classical_only` control is the concrete downgrade: it is what a client
that accepted `ok_T || ok_PQ`, or that skipped the PQ check, would be worth.

Each model runs two handshakes. The first establishes a session; the compromise
happens in phase 1; the second handshake in phase 2 is the one the adversary attacks
with the stolen key. Without that second run a phase-1 leak could not affect any
signature, and the queries would hold vacuously.

Run:  python verification/verifpal/generate_models.py
"""

from __future__ import annotations

import sys
from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parent

PREAMBLE = """\
// {title}
//
// GENERATED by verification/verifpal/generate_models.py -- edit the template there,
// not this file.
//
// {claim}
//
// Verifpal's analysis is bounded: every principal runs two concurrent sessions, and
// a query that holds means no attack was found within that bound, not that none
// exists. Both handshakes below therefore run twice over, four in total.

attacker[active]

principal CA[
    knows private caKey
    caPk = PUBKEY(caKey)
    knows public serverName
]

principal Server[
    knows private skT, skPQ
    pkT = PUBKEY(skT)
    pkPQ = PUBKEY(skPQ)
]

// Enrolment is out of band and guarded: a CA that certifies whatever key arrives on
// an open wire would be an oracle.
Server -> CA: [pkT], [pkPQ]

principal CA[
    certSig = SIGN(caKey, CONCAT(serverName, pkT, pkPQ))
]

CA -> Server: [caPk], [certSig]
CA -> Client: [caPk]

principal Server[
    serverCert = CONCAT(serverName, pkT, pkPQ, certSig)
]

// The certificate reaches the client on the wire; the trust anchor does not.
Server -> Client: serverCert

"""

# One handshake. `tag` keeps the second run's values distinct in the transcript
# comments; Verifpal freshens every `generates` per block, so the two runs share only
# the long-term keys, which is what the compromise phases act on.
HANDSHAKE = """\
// ---- handshake {index} ----
principal Client[
    knows public serverName, ctx
    knows public labelHs
    // ClientHello carries both key shares, both ephemeral.
    generates x{tag}, dkPQ{tag}
    gx{tag} = PUBKEY(x{tag})
    ekPQ{tag} = PUBKEY(dkPQ{tag})
]

Client -> Server: gx{tag}, ekPQ{tag}

principal Server[
    knows public ctx, labelHs
    generates y{tag}, r{tag}
    gy{tag} = PUBKEY(y{tag})
    // Post-quantum branch: encapsulate to the client's ephemeral KEM key.
    ss_pq{tag}, ct{tag} = KEM_ENCAP(ekPQ{tag}, r{tag})
    // Classical branch.
    z_ecdh{tag} = DH_KEX(gx{tag}, y{tag})
    // One hybrid input, fed to the key schedule as TLS 1.3 feeds the ECDHE secret.
    z_hybrid{tag} = CONCAT(z_ecdh{tag}, ss_pq{tag})
    key{tag} = HKDF(nil, z_hybrid{tag}, labelHs)
    // CertificateVerify: both signatures over ONE input, which covers the transcript.
    th{tag} = HASH(gx{tag}, ekPQ{tag}, gy{tag}, ct{tag}, serverCert)
    mcv{tag} = CONCAT(ctx, th{tag})
    sigT{tag} = SIGN(skT, mcv{tag})
    sigPQ{tag} = SIGN(skPQ, mcv{tag})
]

Server -> Client: gy{tag}, ct{tag}, sigT{tag}, sigPQ{tag}

principal Client[
    z_ecdh_c{tag} = DH_KEX(gy{tag}, x{tag})
    ss_pq_c{tag} = KEM_DECAP(dkPQ{tag}, ct{tag})
    z_hybrid_c{tag} = CONCAT(z_ecdh_c{tag}, ss_pq_c{tag})
    key_c{tag} = HKDF(nil, z_hybrid_c{tag}, labelHs)
    certName{tag}, certT{tag}, certPQ{tag}, certSig{tag} = SPLIT(serverCert)
    _ = SIGNVERIF(caPk, CONCAT(certName{tag}, certT{tag}, certPQ{tag}), certSig{tag})?
    mcv_c{tag} = CONCAT(ctx, HASH(gx{tag}, ekPQ{tag}, gy{tag}, ct{tag}, serverCert))
    _ = SIGNVERIF(certT{tag}, mcv_c{tag}, sigT{tag})?
{pq_check}
    // Sent only once every check above has passed, so an agreement query on it is
    // exactly the claim that the client accepted this server.
    generates m{tag}
    c{tag} = AEAD_ENC(key_c{tag}, nil, m{tag}, nil)
]

Client -> Server: c{tag}

principal Server[
    m_s{tag} = AEAD_DEC(key{tag}, nil, c{tag}, nil)?
]

"""

PQ_CHECK_PRESENT = "    _ = SIGNVERIF(certPQ{tag}, mcv_c{tag}, sigPQ{tag})?"
PQ_CHECK_ABSENT = (
    "    // NEGATIVE CONTROL: the post-quantum signature arrives on the wire and is\n"
    "    // never checked. This is what a client that accepted `ok_T || ok_PQ`, or that\n"
    "    // skipped the PQ half, would be running.\n"
)

LEAK_BLOCK = """\
// ---- compromise, declared before the handshake ----
// {description}
principal Server[
{leaks}
]

"""

QUERIES_TEMPLATE = """\
queries[
    // The client's message exists only after every check passed, so its secrecy,
    // restricted to runs in which it was sent, is what the hybrid authentication is
    // supposed to deliver.
    confidentiality? m1[
        precondition[Client -> Server: c1]
    ]
    // Injective agreement on the classical half of the dual signature.
    authentication? Server -> Client: sigT1
{pq_query}    // The session key is per-session.
    freshness? key_c1
    // The last query is the deliberate NON-claim: this design authenticates the
    // server to the client, not the client to the server, so an adversary that
    // completes an unauthenticated key exchange may talk to the server. Its failure
    // is expected in every model and is not a finding.
    authentication? Client -> Server: c1
]
"""

PQ_QUERY = "    // Injective agreement on the post-quantum half.\n    authentication? Server -> Client: sigPQ1\n"


def build(title: str, claim: str, *, pq_check: bool, leaks: str | None, description: str) -> str:
    """Assemble one model file.

    The compromise is declared in phase 0, *before* the handshake, so the adversary
    holds the leaked half while the handshake runs. A leak declared after the
    handshake could not affect a signature that was already made, and the queries
    would hold vacuously.
    """
    check = PQ_CHECK_PRESENT if pq_check else PQ_CHECK_ABSENT
    parts = [PREAMBLE.format(title=title, claim=claim)]
    if leaks is not None:
        parts.append(LEAK_BLOCK.format(description=description, leaks=leaks))
    parts.append(HANDSHAKE.format(index=1, tag="1", pq_check=check.format(tag="1")))
    # A model whose client never computes with sigPQ cannot be asked a question about
    # that signature: Verifpal refuses an authentication query on a value no principal
    # commits to, which is the right call -- there is no such authentication to break.
    parts.append(QUERIES_TEMPLATE.format(pq_query=PQ_QUERY if pq_check else ""))
    return "".join(parts)


MODELS: dict[str, dict[str, object]] = {
    "hybrid_auth.vp": {
        "title": "Hybrid TLS 1.3 dual-signature authentication — no compromise",
        "claim": (
            "Expected: every query HOLDS. This is the baseline the compromised models\n"
            "// are read against."
        ),
        "pq_check": True,
        "leaks": None,
        "description": "",
    },
    "hybrid_auth_classical_leaked.vp": {
        "title": "Hybrid authentication — the CLASSICAL signing key leaks",
        "claim": (
            "Expected: the gated queries still HOLD. The adversary can forge the\n"
            "// classical half of any CertificateVerify but cannot produce the post-quantum\n"
            "// half, so the client halts and never reaches the compromised session's\n"
            "// application key. `authentication? sigT1` is expected to FAIL: that half is\n"
            "// genuinely forgeable, which is why the client does not rely on it alone."
        ),
        "pq_check": True,
        "leaks": "    leaks skT",
        "description": "an adversary holds the classical long-term signing key.",
    },
    "hybrid_auth_pq_leaked.vp": {
        "title": "Hybrid authentication — the POST-QUANTUM signing key leaks",
        "claim": (
            "Expected: the mirror image of the classical-leaked model. Here\n"
            "// `authentication? sigPQ1` is the query that fails and the gated queries still\n"
            "// hold: the classical half carries the session."
        ),
        "pq_check": True,
        "leaks": "    leaks skPQ",
        "description": "an adversary holds the post-quantum long-term signing key.",
    },
    "hybrid_auth_both_leaked.vp": {
        "title": "Hybrid authentication — BOTH signing keys leak (negative control)",
        "claim": (
            "Expected: the gated queries FAIL. This model exists to show the queries\n"
            "// have teeth: with both halves gone the adversary completes the handshake and\n"
            "// the client's message is no longer a two-party secret. A model whose queries\n"
            "// cannot fail establishes nothing."
        ),
        "pq_check": True,
        "leaks": "    leaks skT, skPQ",
        "description": "an adversary holds both long-term signing keys.",
    },
    "hybrid_auth_classical_only.vp": {
        "title": "Classical-only verification with the classical key leaked (downgrade control)",
        "claim": (
            "Expected: the gated queries FAIL. The client here ignores the\n"
            "// post-quantum signature entirely -- the wire format is identical, only the\n"
            "// check is missing -- and with the classical key leaked the adversary walks\n"
            "// through. This is the attack the hybrid construction exists to prevent, and\n"
            "// it is the reason the PQ check may not be optional."
        ),
        "pq_check": False,
        "leaks": "    leaks skT",
        "description": "an adversary holds the classical signing key, and the client does not check the post-quantum half.",
    },
}


def main() -> int:
    """Write every model file and report what was written."""
    written: list[Path] = []
    for name, spec in MODELS.items():
        text = build(
            str(spec["title"]),
            str(spec["claim"]),
            pq_check=bool(spec["pq_check"]),
            leaks=spec["leaks"] if isinstance(spec["leaks"], str) else None,
            description=str(spec["description"]),
        )
        path = OUTPUT_DIR / name
        path.write_text(text, encoding="utf-8")
        written.append(path)
        print(f"wrote {path.name} ({len(text)} bytes)")
    print(f"\n{len(written)} models. Run them with:")
    print("  .tools\\verifpal\\verifpal.exe verify verification\\verifpal\\hybrid_auth*.vp --result-code")
    return 0


if __name__ == "__main__":
    sys.exit(main())
