"""Write a unified diff between two copies of this project.

The improvement plan asks the delivery to carry a **source patch**, not only a full tree, so a
reviewer can see exactly what changed since the revision they audited. This script produces that
patch from two directories, with the same exclusions the package builder uses, and it refuses to
guess: differences in binary files are reported as such rather than embedded.

Usage:
    python tools/make_source_patch.py <old-tree> <new-tree> [--out packaging/v8-to-v9.patch]
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

EXCLUDE_PARTS = {
    ".deps", ".deps-falcon", ".tools", ".venv", "target", "__pycache__", ".pytest_cache",
    ".mypy_cache", ".tmp", ".pytest-tmp", ".bench-lifecycle-quick", "packaging", ".git",
}
EXCLUDE_SUFFIXES = {".pyc", ".pyo", ".zip"}


def tracked_files(root: Path) -> dict[str, Path]:
    files: dict[str, Path] = {}
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if any(part in EXCLUDE_PARTS for part in relative.parts):
            continue
        if not path.is_file() or path.suffix in EXCLUDE_SUFFIXES:
            continue
        files[relative.as_posix()] = path
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("old", help="the tree the reviewer audited")
    parser.add_argument("new", help="the tree being delivered")
    parser.add_argument("--out", default=None, help="write the patch here (default: stdout)")
    parser.add_argument("--label-old", default=None, help="label for the old tree in the diff")
    parser.add_argument("--label-new", default=None, help="label for the new tree in the diff")
    args = parser.parse_args(argv)

    old_root, new_root = Path(args.old).resolve(), Path(args.new).resolve()
    old_files, new_files = tracked_files(old_root), tracked_files(new_root)
    label_old = args.label_old or old_root.name
    label_new = args.label_new or new_root.name

    chunks: list[str] = []
    added = removed = changed = 0
    for name in sorted(set(old_files) | set(new_files)):
        if name not in old_files:
            added += 1
            chunks.append(f"--- /dev/null\n+++ {label_new}/{name}\n")
            body = new_files[name].read_text(encoding="utf-8", errors="replace").splitlines(True)
            chunks.append(f"@@ -0,0 +1,{len(body)} @@\n")
            chunks.extend("+" + line for line in body)
            continue
        if name not in new_files:
            removed += 1
            chunks.append(f"--- {label_old}/{name}\n+++ /dev/null\n")
            body = old_files[name].read_text(encoding="utf-8", errors="replace").splitlines(True)
            chunks.append(f"@@ -1,{len(body)} +0,0 @@\n")
            chunks.extend("-" + line for line in body)
            continue
        old_text = old_files[name].read_text(encoding="utf-8", errors="replace")
        new_text = new_files[name].read_text(encoding="utf-8", errors="replace")
        if old_text == new_text:
            continue
        changed += 1
        diff = difflib.unified_diff(
            old_text.splitlines(True), new_text.splitlines(True),
            fromfile=f"{label_old}/{name}", tofile=f"{label_new}/{name}",
        )
        chunks.extend(diff)

    patch = "".join(chunks)
    header = (
        f"# source patch: {label_old} -> {label_new}\n"
        f"# files added: {added}, removed: {removed}, changed: {changed}\n"
        f"# generated by tools/make_source_patch.py\n"
    )
    text = header + patch
    if args.out:
        out = Path(args.out)
        if not out.is_absolute():
            out = new_root / out
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {out} ({len(text)} bytes; {added} added, {removed} removed, {changed} changed)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
