<#
.SYNOPSIS
  Build the review package: the project, its evidence, and the brief for an external reviewer.

.DESCRIPTION
  Produces `hybrid-tls13-review-package/` beside the project, and optionally a zip of it.

  Excluded, because they are large and reproducible rather than because they are secret:
  the installed dependencies (.deps, .deps-falcon), the Verifpal binary (.tools), and the
  Rust build tree (rust-prototype/target) -- together about 344 MB. The reviewer installs
  the first two from PyPI and rebuilds the third from source.

  Included, because a reviewer cannot check claims without them: every source directory,
  the benchmark outputs the documents cite, the symbolic models and their verdicts, the
  Rust prototype, and the assumption ledger and build note.

  SHA256SUMS.txt covers the project tree, so a reviewer can confirm they read the same
  revision the documents describe.

.EXAMPLE
  powershell -File tools\make_review_package.ps1
  powershell -File tools\make_review_package.ps1 -Zip -Force
#>
[CmdletBinding()]
param(
  # Also produce hybrid-tls13-review-package.zip next to the directory.
  [switch]$Zip,
  # Delete and rebuild the package directory if it already exists.
  [switch]$Force,
  # Directory (and zip) name to build, so a round-2 package does not overwrite round 1.
  [string]$StageName = 'hybrid-tls13-review-package'
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$workspace = Split-Path -Parent $projectRoot
$stage = Join-Path $workspace $StageName
$projectTarget = Join-Path $stage 'project'
$reference = Join-Path $stage 'reference'

# Directories whose contents are regenerated by tools\bootstrap_env.ps1,
# tools\install_falcon_provider.ps1, tools\install_verifpal.ps1 or cargo, plus the scratch
# directories a test or acceptance run leaves behind. `.tmp` was added after the first v7 build
# shipped it: a package must not carry a reviewer a directory of pytest temp junk, and those
# names are also where local paths leak.
$excludedDirs = @('.deps', '.deps-falcon', '.tools', '.venv', 'target', '__pycache__',
                  '.pytest_cache', '.mypy_cache', '.tmp', '.pytest-tmp', 'packaging')
$excludedFiles = @('*.pyc', '*.pyo')

if (Test-Path -LiteralPath $stage) {
  if (-not $Force) { throw "$stage already exists; pass -Force to rebuild it" }
  Remove-Item -LiteralPath $stage -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $projectTarget, $reference | Out-Null

Write-Host "staging : $stage"

# The three reviewer-facing documents live in the project as packaging/ so that rebuilding
# the package cannot destroy them -- the first version of this script wiped its own
# hand-written output on -Force, which is exactly the kind of trap a builder must not set.
$packaging = Join-Path $projectRoot 'packaging'
$reviewerDocs = @('START_HERE.md', 'PACKAGE_MANIFEST.md', 'REVIEW_CHECKLIST.md')
foreach ($doc in $reviewerDocs) {
  if (-not (Test-Path -LiteralPath (Join-Path $packaging $doc))) {
    throw "reviewer document missing from source: packaging\$doc"
  }
}

# robocopy expresses exclusions as directory and file names; its exit codes 0..7 mean
# success with varying degrees of "things were copied", so only >=8 is a failure.
$robocopyArgs = @(
  $projectRoot, $projectTarget, '/E', '/NFL', '/NDL', '/NJH', '/NJS', '/NP',
  '/XD'
) + $excludedDirs + @('/XF') + $excludedFiles
& robocopy @robocopyArgs | Out-Null
if ($LASTEXITCODE -ge 8) { throw "robocopy failed with exit code $LASTEXITCODE" }
Write-Host "copied  : project tree (excluding $($excludedDirs -join ', '))"

# The design note is the specification of record; the papers are background reading.
#
# The match is deliberately ASCII-only. It used to glob the Chinese part of the filename,
# which silently stopped matching the moment this script was saved without a UTF-8 BOM:
# Windows PowerShell 5.1 reads a BOM-less script as ANSI, so the literal arrived as
# mojibake and the package quietly shipped without its design note. Matching the ASCII
# prefix (plus a size floor, to skip a stray .html) cannot be broken by an encoding
# decision, and this file is kept free of non-ASCII characters for the same reason.
$designNote = Get-ChildItem -LiteralPath $workspace -File -Filter 'TLS1.3_*.html' -ErrorAction SilentlyContinue |
  Where-Object { $_.Length -gt 4KB } |
  Select-Object -First 1
if (-not $designNote) {
  # Fallback: any .html in the workspace root that is not this project's own demo.
  $designNote = Get-ChildItem -LiteralPath $workspace -File -Filter '*.html' -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notlike 'hybrid-tls13-*' -and $_.Length -gt 4KB } |
    Select-Object -First 1
}
if (-not $designNote) { Write-Warning 'design note not found in the workspace; the package will omit it' }
if ($designNote) {
  $noteDir = Join-Path $reference 'design-note'
  New-Item -ItemType Directory -Force -Path $noteDir | Out-Null
  Copy-Item -LiteralPath $designNote.FullName -Destination $noteDir
  Write-Host "copied  : design note ($($designNote.Name))"
}

$papers = @('kemtls.pdf', 'KEMTLS-PDK.pdf', 'Celi2021.pdf')
$paperDir = Join-Path $reference 'papers'
New-Item -ItemType Directory -Force -Path $paperDir | Out-Null
$copiedPapers = 0
foreach ($paper in $papers) {
  $source = Join-Path $workspace $paper
  if (Test-Path -LiteralPath $source) {
    Copy-Item -LiteralPath $source -Destination $paperDir
    $copiedPapers++
  }
}
Write-Host "copied  : $copiedPapers background papers (the bilingual KEMTLS PDF is omitted: same paper)"

Copy-Item -Path (Join-Path $packaging '*') -Destination $stage -Force
Write-Host "copied  : $($reviewerDocs.Count) reviewer documents from packaging/"

# Hashes over the project tree, so a reviewer can confirm the revision.
#
# Written without a BOM on purpose. `Set-Content -Encoding UTF8` emits one, and a BOM in the
# first line makes `sha256sum -c` reject the file as unparsable and makes a naive
# "split on whitespace" verifier compare the BOM against the hash. The previous packages
# carried it; a reviewer-facing artefact has to be readable by the tools reviewers use.
$hashFile = Join-Path $stage 'SHA256SUMS.txt'
$lines = Get-ChildItem -LiteralPath $projectTarget -Recurse -File |
  Sort-Object FullName |
  ForEach-Object {
    $relative = $_.FullName.Substring($projectTarget.Length + 1).Replace('\', '/')
    $hash = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLower()
    "$hash  $relative"
  }
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($hashFile, [string[]]$lines, $utf8NoBom)
Write-Host "hashed  : $($lines.Count) files -> SHA256SUMS.txt"

if ($Zip) {
  $zipPath = Join-Path $workspace ($StageName + '.zip')
  if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }
  Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zipPath -CompressionLevel Optimal
  $size = (Get-Item -LiteralPath $zipPath).Length / 1MB
  Write-Host ("zipped  : {0} ({1:N2} MB)" -f $zipPath, $size)
}

Write-Host ''
Write-Host 'Package contents:'
Get-ChildItem -LiteralPath $stage | ForEach-Object {
  if ($_.PSIsContainer) {
    $size = (Get-ChildItem -LiteralPath $_.FullName -Recurse -File | Measure-Object -Sum Length).Sum
    "  {0,-28}{1,10:N0} KB" -f $_.Name, ($size / 1KB)
  } else {
    "  {0,-28}{1,10:N0} KB" -f $_.Name, ($_.Length / 1KB)
  }
}
