"""Functional acceptance for record streaming, byte identity and CA audit closure.

No benchmark samples or SLH signatures are generated by this module.
"""
import datetime as dt
import hashlib
import hmac
import sys
from pathlib import Path

import pytest
from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import ExtendedKeyUsageOID, ObjectIdentifier

from tls import pki
from tls.alt_chain import issue_alt_certificate
from tls.config import HybridTLSConfig
from tls.credentials import CertificateAuthority, ServerCredentials
from tls.errors import BackendUnavailableError, HandshakeError
from tls.handshake.client import HybridClient
from tls.handshake.connection import HybridConnection
from tls.handshake.server import HybridServer
from tls.pq.slhdsa_sm3 import SlhDsaSm3
from tls.record.aead import CONTENT_TYPE_HANDSHAKE, MAX_CONTENT_BYTES, RecordLayer, get_aead_suite


def record_layer():
    return RecordLayer(get_aead_suite("aes-128-gcm"), bytes(16), bytes(12))


@pytest.mark.parametrize("size", [0, 1, 16383, 16384])
def test_record_content_boundary_and_actual_serialized_overhead(size):
    sender, receiver = record_layer(), record_layer()
    record = sender.seal(CONTENT_TYPE_HANDSHAKE, b"x" * size)
    assert len(record) == size + 17
    assert receiver.open(record, CONTENT_TYPE_HANDSHAKE) == (CONTENT_TYPE_HANDSHAKE, b"x" * size)
    assert sender.sequence == receiver.sequence == 1


def test_oversize_record_rejected_before_sequence_is_consumed():
    sender, receiver = record_layer(), record_layer()
    with pytest.raises(HandshakeError, match="16384"):
        sender.seal(CONTENT_TYPE_HANDSHAKE, bytes(16385))
    with pytest.raises(HandshakeError, match="16640"):
        receiver.open(bytes(16641), CONTENT_TYPE_HANDSHAKE)
    # Craft authenticated overlong plaintext independently, bypassing seal's cap.
    ciphertext = sender._aead.encrypt(sender._nonce(), bytes(16385) + bytes([22]),
                                     sender._additional_data(22, 16386))
    with pytest.raises(HandshakeError, match="16384"):
        receiver.open(ciphertext, CONTENT_TYPE_HANDSHAKE)
    assert sender.sequence == receiver.sequence == 0


def long_classical_chain(leaf_key, identity="server.example"):
    root_key = ec.generate_private_key(ec.SECP256R1())
    common = dict(issuer_name=pki._name("long-test-root"), signing_key=root_key,
                  authority_key_identifier=None)
    root = pki._issue(subject="long-test-root", subject_public_key=root_key.public_key(),
                      ca=True, path_length=0, **common)
    leaf = pki._issue(subject=identity, subject_public_key=leaf_key.public_key(),
        ca=False, path_length=None, extra_extensions=[
            x509.SubjectAlternativeName([x509.DNSName(identity)]),
            x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]),
            x509.UnrecognizedExtension(ObjectIdentifier("1.3.6.1.4.1.99999.77"), bytes(40000))], **common)
    encode = lambda c: c.public_bytes(serialization.Encoding.DER)
    return pki.CertificateChain((encode(leaf),), encode(root), root_key.public_key(), encode(leaf))


def session(monkeypatch):
    config = HybridTLSConfig(pq_enabled=False, x509=True)
    monkeypatch.setattr(ServerCredentials, "_build_chain",
                        lambda self: long_classical_chain(self.classical_secret))
    authority = CertificateAuthority(config.classical())
    credentials = ServerCredentials(config)
    client = HybridClient(config, authority,
                          trusted_root=x509.load_der_x509_certificate(credentials.chain.root_der))
    server = HybridServer(config, credentials, credentials.bind_to(authority))
    client.receive_server_hello(server.receive_client_hello(client.create_client_hello()))
    return client, server, config


def test_long_valid_der_chain_fragments_without_changing_transcript(monkeypatch):
    client, server, _ = session(monkeypatch)
    flight = server.send_authenticated_flight()
    assert len([row for row in flight if row[0] == "Certificate"]) == 3
    assert all(len(fragment) <= MAX_CONTENT_BYTES for _, _, fragment in flight)
    client.receive_server_flight([record for _, record, _ in flight])
    assert client.server_flight_complete
    assert client.transcript.hash() == server.transcript.hash()
    assert client.server_records.sequence == server.server_records.sequence == len(flight)
    server.receive_client_finished(client.send_client_finished())
    assert client.exporter_secret("test", b"") == server.exporter_secret("test", b"")


def test_streaming_accepts_split_headers_and_coalesced_messages(monkeypatch):
    client, server, _ = session(monkeypatch)
    source = server.send_authenticated_flight()
    plaintext = b"".join(fragment for _, _, fragment in source)
    # Re-seal the exact transcript with independent fresh sequence state. First
    # header spans records; later records straddle complete-message boundaries.
    original = server.server_records
    sender = RecordLayer(original.suite, original._key, original._iv)
    fragments = [plaintext[:2], plaintext[2:3]]
    fragments += [plaintext[start:start + 14000] for start in range(3, len(plaintext), 14000)]
    for fragment in fragments:
        client.receive_server_record(sender.seal(CONTENT_TYPE_HANDSHAKE, fragment))
    client.finish_server_flight()
    assert client.transcript.hash() == server.transcript.hash()
    assert client.server_records.sequence == len(fragments)


@pytest.mark.parametrize("failure", ["truncate", "swap", "tamper", "append"])
def test_fragment_stream_rejects_incomplete_reordered_or_modified_records(monkeypatch, failure):
    client, server, _ = session(monkeypatch)
    records = [record for _, record, _ in server.send_authenticated_flight()]
    if failure == "truncate":
        records = records[:-1]
    elif failure == "swap":
        records[1], records[2] = records[2], records[1]
    elif failure == "tamper":
        records[2] = records[2][:-1] + bytes([records[2][-1] ^ 1])
    else:
        records.append(records[-1])
    with pytest.raises(HandshakeError):
        client.receive_server_flight(records)


def test_p0_never_constructs_optional_providers_and_counts_actual_records(monkeypatch):
    def forbidden(self):
        pytest.fail("pure classical P0 constructed a disabled provider")
    monkeypatch.setattr(HybridTLSConfig, "kem_backend", forbidden)
    monkeypatch.setattr(HybridTLSConfig, "pq", forbidden)
    result = HybridConnection.run(HybridTLSConfig(pq_enabled=False))
    assert result.application_payload_ok and result.exporters_match
    assert result.kem is result.pq_signer is None
    assert result.handshake_bytes == result.plaintext_bytes + 5 * 17
    assert sum(x.tcp_framed_bytes for x in result.messages) == result.handshake_bytes + 7 * 4
    assert sum(x.standard_tls_model_bytes for x in result.messages) == result.handshake_bytes + 7 * 5


def test_long_chain_tcp_receives_until_finished_and_counts_length_prefixes(monkeypatch):
    from tls.transport.tcp import run_over_tcp
    monkeypatch.setattr(ServerCredentials, "_build_chain",
                        lambda self: long_classical_chain(self.classical_secret))
    # Functional loopback only; no link shaping, distributions or latency samples.
    result = run_over_tcp(HybridTLSConfig(pq_enabled=False, x509=True), timeout_seconds=5)
    assert result.error is None and result.application_ok
    assert len([row for row in result.messages if row.name == "Certificate"]) == 3
    assert result.handshake_bytes == sum(x.total_bytes for x in result.messages)
    assert all(x.protection_bytes == 17 for x in result.messages if x.name not in ("ClientHello", "ServerHello"))
    assert all(x.total_bytes == x.tcp_framed_bytes for x in result.messages)


def test_require_native_fails_explicitly_without_python_fallback(monkeypatch):
    signer = SlhDsaSm3(require_native=True, library="intentionally-missing-native-library")
    def forbidden(*args):
        pytest.fail("required native verification silently fell back")
    monkeypatch.setattr(signer, "_modules", forbidden)
    monkeypatch.setattr(signer, "_native", lambda: (_ for _ in ()).throw(BackendUnavailableError("missing")))
    with pytest.raises(BackendUnavailableError):
        signer.verify(bytes(32), b"message", bytes(3856))
    with pytest.raises(ValueError, match="mutually exclusive"):
        SlhDsaSm3(require_native=True, force_python=True)


class TestOnlySigner:
    """Small test authenticator for callback control flow, never an SLH provider."""
    name = "ml-dsa-44"
    signature_bytes = 32
    def sign(self, secret, message):
        return hmac.digest(secret, message, "sha256")
    def verify(self, public, message, signature):
        return hmac.compare_digest(self.sign(public, message), signature)


@pytest.mark.parametrize("failure", [None, "sign", "verify", "assemble"])
def test_ca_budget_finalized_once_with_digest_on_success_and_charged_failure(tmp_path, monkeypatch, failure):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from tools.signing_budget import SigningBudget
    from tls import alt_chain
    ledger = SigningBudget(tmp_path / "test-ca.sqlite")
    signer = TestOnlySigner()
    if failure == "sign":
        monkeypatch.setattr(signer, "sign", lambda *args: (_ for _ in ()).throw(ValueError("sign failed")))
    elif failure == "verify":
        monkeypatch.setattr(signer, "verify", lambda *args: False)
    elif failure == "assemble":
        original = alt_chain._issue_fixed
        def assemble(*args, **kwargs):
            if any(getattr(x, "oid", None) == alt_chain.ALT_SIGNATURE_VALUE for x in kwargs.get("extra", ())):
                raise ValueError("assembly failed")
            return original(*args, **kwargs)
        monkeypatch.setattr(alt_chain, "_issue_fixed", assemble)
    key = ec.generate_private_key(ec.SECP256R1())
    now = dt.datetime.now(dt.UTC)
    options = dict(name=signer.name, signer=signer, secret_key=b"test-key", issuer_public_key=b"test-key",
        before_sign=ledger.reserve, after_sign=ledger.finish, subject="test", issuer=alt_chain._name("test"),
        subject_key=key.public_key(), issuer_key=key, ca=True, path_length=0, serial=123,
        valid_from=now - dt.timedelta(days=1), valid_to=now + dt.timedelta(days=1))
    if failure:
        with pytest.raises(ValueError):
            issue_alt_certificate(**options)
    else:
        certificate = issue_alt_certificate(**options)
        from tls.der import bit_string_bytes
        signature = bit_string_bytes(certificate.extensions.get_extension_for_oid(alt_chain.ALT_SIGNATURE_VALUE).value.value)
    state = ledger.status()[0]
    assert state["used"] == 1 and state["count_reconciled"]
    assert state["states"] == {"failed" if failure else "committed": 1}
    with ledger.connection() as database:
        row = database.execute("SELECT signature_sha256 FROM reservations").fetchone()
    assert row[0] == (None if failure else hashlib.sha256(signature).hexdigest())
