"""Generate and retain bounded CA-binding/online-authentication model evidence.

This is symbolic functional verification, with no implementation performance
sampling. A reported attack is a result, not a tool execution failure.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
MODELS = ROOT / "base_tls/verification/ca_models"
SCENARIOS = {
    "M1_honest": (False, False, False, False, False, False),
    "M2_honest": (True, False, False, False, False, False),
    "M1_ca_leaked": (False, True, False, False, False, False),
    "M2_ca_leaked": (True, True, False, False, False, False),
    "M1_all_classical": (False, True, True, False, False, False),
    "M2_all_classical": (True, True, True, False, False, False),
    "M2_dual_all_classical": (True, True, True, True, False, False),
    "control_alt_disabled": (False, True, False, False, False, False),
    "control_all_ca_leaked": (True, True, False, False, True, False),
    "control_both_online_leaked": (True, True, True, True, False, True),
}
QUERY_MAP = [
    {"name": "Binding", "query": "authentication? Intermediate -> Client: leafTBS",
     "meaning": "Accepted leaf identity, online keys, algorithms, use and validity have an issuing-CA transmission; this injective query is stronger than reusable-certificate authorization."},
    {"name": "LiveAuth", "query": "authentication? Server -> Client: onlineSignature",
     "meaning": "Accepted online classical proof was transmitted by Server for this transcript."},
    {"name": "Fresh", "query": "freshness? transcriptClient",
     "meaning": "The accepted transcript includes fresh client/server random values and ephemeral shares."},
    {"name": "Secret", "query": "confidentiality? applicationMessage",
     "meaning": "Application plaintext sent after certificate, online proof and Finished checks remains secret."},
]


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def model(name, options):
    alt, ca_leak, online_leak, dual, alt_leak, pq_online_leak = options
    root_leaks = "    leaks rootClassical\n" if ca_leak else ""
    intermediate_leaks = "    leaks intermediateClassical\n" if ca_leak else ""
    if alt_leak:
        root_leaks += "    leaks rootAlternative\n"
        intermediate_leaks += "    leaks intermediateAlternative\n"
    server_leaks = "    leaks onlineClassical\n" if online_leak else ""
    if pq_online_leak:
        server_leaks += "    leaks onlineAlternative\n"
    alt_checks = """    _ = SIGNVERIF(rootAlternativePk, receivedIntermediateTBS, receivedIntermediateAltSig)?
    _ = SIGNVERIF(receivedIntermediateAltPk, leafTBS, receivedLeafAltSig)?
""" if alt else ""
    pq_check = "    _ = SIGNVERIF(receivedOnlineAltPk, cvClient, onlineAltSignature)?\n" if dual else ""
    return f"""// {name}; generated by tools/run_ca_models.py.
// Classical/alternative signatures are distinct ideal keys of SIGN.
// Only local root keys and enrollment are guarded. Leaf keys are wire inputs.
// Policy is local; DER/expiry arithmetic/revocation are implementation checks.
attacker[active]

principal RootCA[
    knows private rootClassical, rootAlternative
    rootClassicalPk = PUBKEY(rootClassical)
    rootAlternativePk = PUBKEY(rootAlternative)
    knows public issuerName, caUse, caValidity, caAlgorithms
]
principal Intermediate[
    knows private intermediateClassical, intermediateAlternative
    intermediateClassicalPk = PUBKEY(intermediateClassical)
    intermediateAlternativePk = PUBKEY(intermediateAlternative)
    knows public issuerName, caUse, caValidity, caAlgorithms
]
Intermediate -> RootCA: [intermediateClassicalPk], [intermediateAlternativePk]
principal RootCA[
    intermediateKeys = CONCAT(intermediateClassicalPk, intermediateAlternativePk)
    intermediatePolicy = CONCAT(caUse, caValidity, caAlgorithms)
    intermediateTBS = CONCAT(issuerName, intermediateKeys, intermediatePolicy)
    intermediateSig = SIGN(rootClassical, intermediateTBS)
    intermediateAltSig = SIGN(rootAlternative, intermediateTBS)
    intermediateCertificate = CONCAT(intermediateTBS, intermediateSig, intermediateAltSig)
{root_leaks}]
RootCA -> Client: [rootClassicalPk], [rootAlternativePk], intermediateCertificate

principal Server[
    knows private onlineClassical, onlineAlternative
    onlineClassicalPk = PUBKEY(onlineClassical)
    onlineAlternativePk = PUBKEY(onlineAlternative)
    knows public identity, serverUse, serverValidity, onlineAlgorithms
]
Server -> Intermediate: [onlineClassicalPk], [onlineAlternativePk]
principal Intermediate[
    knows public identity, serverUse, serverValidity, onlineAlgorithms
    onlineKeys = CONCAT(onlineClassicalPk, onlineAlternativePk)
    leafPolicy = CONCAT(serverUse, serverValidity, onlineAlgorithms)
    leafTBS = CONCAT(identity, onlineKeys, leafPolicy)
    leafSig = SIGN(intermediateClassical, leafTBS)
    leafAltSig = SIGN(intermediateAlternative, leafTBS)
{intermediate_leaks}]
Intermediate -> Server: [leafTBS], [leafSig], [leafAltSig]
// This unguarded message represents transport of the issuing CA's certificate.
Intermediate -> Client: leafTBS, leafSig, leafAltSig

principal Client[
    knows public issuerName, caUse, caValidity, caAlgorithms
    knows public identity, serverUse, serverValidity, onlineAlgorithms, cvContext, hsLabel, finishedLabel, appLabel
    receivedIntermediateTBS, receivedIntermediateSig, receivedIntermediateAltSig = SPLIT(intermediateCertificate)?
    receivedIssuer, receivedIntermediateKeys, receivedIntermediatePolicy = SPLIT(receivedIntermediateTBS)?
    receivedIntermediateClassicalPk, receivedIntermediateAltPk = SPLIT(receivedIntermediateKeys)?
    _ = ASSERT(receivedIssuer, issuerName)?
    _ = ASSERT(receivedIntermediatePolicy, CONCAT(caUse, caValidity, caAlgorithms))?
    _ = SIGNVERIF(rootClassicalPk, receivedIntermediateTBS, receivedIntermediateSig)?
    receivedIdentity, receivedOnlineKeys, receivedPolicy = SPLIT(leafTBS)?
    receivedOnlineClassicalPk, receivedOnlineAltPk = SPLIT(receivedOnlineKeys)?
    receivedLeafSig = CONCAT(leafSig, leafAltSig)
    receivedLeafClassicalSig, receivedLeafAltSig = SPLIT(receivedLeafSig)?
    _ = ASSERT(receivedIdentity, identity)?
    _ = ASSERT(receivedPolicy, CONCAT(serverUse, serverValidity, onlineAlgorithms))?
    _ = SIGNVERIF(receivedIntermediateClassicalPk, leafTBS, receivedLeafClassicalSig)?
{alt_checks}    generates clientRandom, clientEphemeral, clientKemSecret
    clientShare = PUBKEY(clientEphemeral)
    clientKemPk = PUBKEY(clientKemSecret)
]
Client -> Server: clientRandom, clientShare, clientKemPk
principal Server[
    knows public cvContext, hsLabel, finishedLabel, appLabel
{server_leaks}    generates serverRandom, serverEphemeral, encapsulationRandom
    serverShare = PUBKEY(serverEphemeral)
    kemSecret, kemCiphertext = KEM_ENCAP(clientKemPk, encapsulationRandom)
    dhSecret = DH_KEX(clientShare, serverEphemeral)
    handshakeKey = HKDF(nil, CONCAT(dhSecret, kemSecret), hsLabel)
    clientHello = CONCAT(clientRandom, clientShare, clientKemPk)
    serverHello = CONCAT(serverRandom, serverShare, kemCiphertext)
    certificateTranscript = CONCAT(leafTBS, leafSig, leafAltSig)
    transcriptServer = HASH(clientHello, serverHello, certificateTranscript, onlineAlgorithms)
    cvServer = CONCAT(cvContext, transcriptServer)
    onlineSignature = SIGN(onlineClassical, cvServer)
    onlineAltSignature = SIGN(onlineAlternative, cvServer)
    finishedKey = HKDF(nil, handshakeKey, finishedLabel)
    serverFinished = MAC(finishedKey, HASH(transcriptServer, onlineSignature, onlineAltSignature))
]
Server -> Client: serverRandom, serverShare, kemCiphertext, onlineSignature, onlineAltSignature, serverFinished
principal Client[
    clientHelloReceived = CONCAT(clientRandom, clientShare, clientKemPk)
    serverHelloReceived = CONCAT(serverRandom, serverShare, kemCiphertext)
    certificateReceived = CONCAT(leafTBS, leafSig, leafAltSig)
    transcriptClient = HASH(clientHelloReceived, serverHelloReceived, certificateReceived, onlineAlgorithms)
    cvClient = CONCAT(cvContext, transcriptClient)
    _ = SIGNVERIF(receivedOnlineClassicalPk, cvClient, onlineSignature)?
{pq_check}    dhClient = DH_KEX(serverShare, clientEphemeral)
    kemClient = KEM_DECAP(clientKemSecret, kemCiphertext)
    handshakeKeyClient = HKDF(nil, CONCAT(dhClient, kemClient), hsLabel)
    finishedKeyClient = HKDF(nil, handshakeKeyClient, finishedLabel)
    _ = ASSERT(serverFinished, MAC(finishedKeyClient, HASH(transcriptClient, onlineSignature, onlineAltSignature)))?
    applicationKeyClient = HKDF(nil, handshakeKeyClient, appLabel)
    generates applicationMessage
    appRecord = AEAD_ENC(applicationKeyClient, nil, applicationMessage, transcriptClient)
]
Client -> Server: appRecord
principal Server[
    applicationKey = HKDF(nil, handshakeKey, appLabel)
    deliveredMessage = AEAD_DEC(applicationKey, nil, appRecord, transcriptServer)?
]
queries[
    authentication? Intermediate -> Client: leafTBS[precondition[Client -> Server: appRecord]]
    authentication? Server -> Client: onlineSignature[precondition[Client -> Server: appRecord]]
    freshness? transcriptClient
    confidentiality? applicationMessage[precondition[Client -> Server: appRecord]]
]
"""


def generate():
    MODELS.mkdir(parents=True, exist_ok=True)
    for name, options in SCENARIOS.items():
        (MODELS / (name + ".vp")).write_text(model(name, options), encoding="utf-8", newline="\n")
    (MODELS / "queries.json").write_text(json.dumps({"schema": "a15-ca-query-map-v1", "queries": QUERY_MAP,
        "policy": "Local fixed policy and checked symbolic use/validity/algorithm labels; no numeric expiry or DER proof.",
        "certificate_reuse": "Binding authentication is injective. Replay of a legitimately reusable certificate can fail that stronger query at sessions>1; inspect traces before calling it unauthorized binding.",
        "dual_online": "Additional online alternative proof is separate from CA alternative signing; 128-24 is CA-only.",
        "honest_execution": "Every checked SIGNVERIF/ASSERT/AEAD_DEC matches in the unsubstituted symbolic execution; functional honest CA/TLS runs are retained separately.",
        "scenarios": {name: dict(zip(("require_alt", "classical_ca_leaked", "classical_online_leaked", "require_dual_online", "alternative_ca_leaked", "alternative_online_leaked"), options)) for name, options in SCENARIOS.items()}}, indent=2) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate-only", action="store_true")
    parser.add_argument("--verifier", type=Path)
    parser.add_argument("--run-dir", type=Path)
    parser.add_argument("--sessions", type=int, choices=(1, 2, 3), default=1)
    parser.add_argument("--models", nargs="+", choices=tuple(SCENARIOS), default=list(SCENARIOS))
    args = parser.parse_args()
    generate()
    if args.generate_only:
        return 0
    if args.verifier is None or args.run_dir is None:
        parser.error("--verifier and a new --run-dir are required")
    out = args.run_dir.resolve()
    out.mkdir(parents=True, exist_ok=False)
    verifier = args.verifier.resolve()
    version = subprocess.check_output([str(verifier), "about"], text=True)
    before = {p.relative_to(ROOT).as_posix(): sha(p) for p in [Path(__file__).resolve(), *sorted(MODELS.glob("*"))]}
    manifest = dict(schema="a15-ca-symbolic-run-v1", started_utc=datetime.now(timezone.utc).isoformat(),
        verifier_version=version, verifier_sha256=sha(verifier), sessions=args.sessions,
        source_sha256=before, runs=[], real_timing_samples=0, formal_performance_started=False,
        scope="Bounded ideal-primitives search; implementation/DER and unbounded security are separate.")
    (out / "verifier-about.txt").write_text(version, encoding="utf-8")
    for name in args.models:
        print(json.dumps({"phase": "ca-symbolic", "model": name, "sessions": args.sessions}), flush=True)
        path = MODELS / (name + ".vp")
        command = [str(verifier), "verify", str(path), "--sessions", str(args.sessions), "--color", "never", "--result-code"]
        with (out / (name + ".first.txt")).open("xb") as stream:
            completed = subprocess.run(command, stdout=stream, stderr=subprocess.STDOUT, timeout=900)
        raw = (out / (name + ".first.txt")).read_text(encoding="utf-8")
        result_code = raw.splitlines()[-1] if raw.splitlines() else ""
        row = dict(model=name, command=command, returncode=completed.returncode, result_code=result_code,
                   raw_sha256=sha(out / (name + ".first.txt")), model_sha256=sha(path))
        if completed.returncode == 0:
            structured_command = [str(verifier), "verify", str(path), "--sessions", str(args.sessions), "--format", "json"]
            with (out / (name + ".json")).open("xb") as stream:
                structured = subprocess.run(structured_command, stdout=stream, stderr=subprocess.STDOUT, timeout=900)
            row.update(json_command=structured_command, json_returncode=structured.returncode,
                       json_sha256=sha(out / (name + ".json")))
        manifest["runs"].append(row)
        (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(row), flush=True)
    manifest["completed_utc"] = datetime.now(timezone.utc).isoformat()
    manifest["source_unchanged"] = all(sha(ROOT / name) == digest for name, digest in before.items())
    manifest["tool_runs_completed"] = manifest["source_unchanged"] and all(r["returncode"] == 0 and r.get("json_returncode") == 0 for r in manifest["runs"])
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return int(not manifest["tool_runs_completed"])


if __name__ == "__main__":
    raise SystemExit(main())
